### ISSUE TITLE
As a team that worked hard on this project we want a website that has neat style so that people using it will appreciate the project. 21

### ISSUE THREAD

**Issue by LucNsabimana** [code4policy/2024-b4-inequality#43]

**Comment by AGolan84** [comment]
- [x]  Independent - Focused on the visual part.
- [x]  Negotiable - The way to display could diverse.
- [x]  Valuable - Gives pride for the hard working team members.
- [x]  Estimable - Based on previous work in class + some extras.
- [x]  Small - Directed to the colors and shapes.
- [x]  Testable - Asking people if they appreciate the looks of the project.

**Definition of done:**
- [ ] A coherent text and color style for the pages that at least 10 people said it looks good.
